intent:
  data_science:
  - major
  - minor
  - major
  - id: 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
    intent: major
  external:
  - major
  - minor
  - minor
  - id: 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
    intent: major
  internal:
  - major
  - minor
  - minor
  - id: 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
    intent: major
