intent:
  data_science:
  - id: f2
    intent: minor
  - id: f4
    intent: minor
  external:
  - id: f1
    intent: minor
  - id: f3
    intent: major
  - id: dev-f5
    intent: major
  internal:
  - id: f1
    intent: major
  - id: f3
    intent: major
  - id: f4
    intent: minor