intent:
  data_science:
  - id: f1
    intent: major
  - id: f2
    intent: major
  - id: f1
    intent: minor
  external:
  - id: f1
    intent: major
  - id: f2
    intent: major
  - id: f1
    intent: minor
  internal:
  - id: f1
    intent: major
  - id: f2
    intent: major
  - id: f1
    intent: minor
